name: Docker Build on Feature Branches

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Junior/GHA-J-2/prerequisites
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t my-app-image .
